export const deploymentGuide = {
  localSetup: {
    title: 'Local Development Setup',
    steps: [
      {
        step: 1,
        title: 'Clone the Repository',
        description: 'Get the source code from your version control system.',
        commands: ['git clone <repository-url>', 'cd vertex-pm']
      },
      {
        step: 2,
        title: 'Install Dependencies',
        description: 'Install all required npm packages.',
        commands: ['npm install', '# or', 'bun install']
      },
      {
        step: 3,
        title: 'Setup Supabase',
        description: 'Start local Supabase instance for development.',
        commands: [
          '# Install Supabase CLI',
          'npm install -g supabase',
          '',
          '# Start local Supabase',
          'supabase start',
          '',
          '# Apply migrations',
          'supabase db push'
        ]
      },
      {
        step: 4,
        title: 'Configure Environment',
        description: 'Environment variables are auto-generated by Supabase integration.',
        commands: [
          '# .env file is auto-generated with:',
          '# VITE_SUPABASE_URL',
          '# VITE_SUPABASE_PUBLISHABLE_KEY',
          '# VITE_SUPABASE_PROJECT_ID'
        ]
      },
      {
        step: 5,
        title: 'Start Development Server',
        description: 'Run the application in development mode.',
        commands: ['npm run dev', '# App available at http://localhost:5173']
      }
    ]
  },
  
  environmentVariables: {
    title: 'Environment Variables',
    variables: [
      {
        name: 'VITE_SUPABASE_URL',
        required: true,
        description: 'Supabase project URL',
        example: 'http://localhost:54321'
      },
      {
        name: 'VITE_SUPABASE_PUBLISHABLE_KEY',
        required: true,
        description: 'Supabase anonymous/public key',
        example: 'eyJhbGciOiJIUzI1NiIs...'
      },
      {
        name: 'VITE_SUPABASE_PROJECT_ID',
        required: true,
        description: 'Supabase project identifier',
        example: 'abcdefghijklmnop'
      },
      {
        name: 'VITE_SITE_ACCESS_KEY',
        required: false,
        description: 'Site-wide access password',
        example: 'your-secure-key'
      }
    ]
  },
  
  productionDeployment: {
    title: 'Production Deployment',
    options: [
      {
        name: 'Lovable Hosting',
        description: 'Recommended for simplest deployment. Click "Publish" in Lovable editor.',
        steps: [
          'Make all code changes in Lovable',
          'Click "Publish" button in top-right',
          'Configure custom domain in Settings',
          'SSL is automatically provisioned'
        ]
      },
      {
        name: 'Self-Hosted Docker',
        description: 'Deploy on your own infrastructure with Docker.',
        steps: [
          'Build production image: docker build -t vertex-pm .',
          'Configure environment variables',
          'Run container: docker run -p 3000:3000 vertex-pm',
          'Setup reverse proxy (nginx/traefik)',
          'Configure SSL certificates'
        ]
      },
      {
        name: 'Static Hosting',
        description: 'Deploy to any static hosting provider.',
        steps: [
          'Build: npm run build',
          'Output is in dist/ folder',
          'Upload to Netlify/Vercel/S3',
          'Configure SPA routing (redirect all to index.html)',
          'Set environment variables in hosting dashboard'
        ]
      }
    ]
  },
  
  supabaseSetup: {
    title: 'Supabase Production Setup',
    steps: [
      {
        title: 'Database Configuration',
        items: [
          'Create Supabase project at supabase.com (or self-host)',
          'Run all migrations from supabase/migrations/',
          'Verify RLS policies are enabled',
          'Configure database backups'
        ]
      },
      {
        title: 'Authentication Setup',
        items: [
          'Configure allowed redirect URLs',
          'Enable email confirmation (or disable for development)',
          'Setup OAuth providers if needed (Google, GitHub)',
          'Configure password policies'
        ]
      },
      {
        title: 'Edge Functions',
        items: [
          'Deploy edge functions: supabase functions deploy',
          'Configure function secrets',
          'Set up webhooks for Git integration',
          'Configure CORS if needed'
        ]
      },
      {
        title: 'Storage Setup',
        items: [
          'Create required storage buckets',
          'Configure storage policies',
          'Set file size limits',
          'Configure CDN if needed'
        ]
      }
    ]
  },
  
  troubleshooting: {
    title: 'Common Issues & Solutions',
    issues: [
      {
        problem: 'Build fails with TypeScript errors',
        solution: 'Run `npm run typecheck` to see detailed errors. Ensure all dependencies are installed.'
      },
      {
        problem: 'Database connection refused',
        solution: 'Verify Supabase is running (`supabase status`). Check environment variables.'
      },
      {
        problem: 'Authentication not working',
        solution: 'Check Supabase auth settings. Verify redirect URLs include your domain.'
      },
      {
        problem: 'RLS blocking all queries',
        solution: 'Verify user is authenticated. Check RLS policies match your use case.'
      },
      {
        problem: 'Edge functions timing out',
        solution: 'Check function logs. Optimize database queries. Consider increasing timeout.'
      },
      {
        problem: 'Git integration not syncing',
        solution: 'Verify webhook is configured. Check OAuth token is valid. Review sync logs.'
      },
      {
        problem: 'Slow board performance',
        solution: 'Check issue count. Consider adding database indexes. Enable query caching.'
      }
    ]
  },
  
  maintenance: {
    title: 'Maintenance Tasks',
    tasks: [
      {
        task: 'Database Backups',
        frequency: 'Daily',
        description: 'Supabase provides automatic daily backups. For self-hosted, configure pg_dump.'
      },
      {
        task: 'Log Rotation',
        frequency: 'Weekly',
        description: 'Archive and rotate application and database logs to manage storage.'
      },
      {
        task: 'Security Updates',
        frequency: 'Monthly',
        description: 'Update dependencies with `npm update`. Review security advisories.'
      },
      {
        task: 'Performance Review',
        frequency: 'Monthly',
        description: 'Review slow queries. Analyze error rates. Check resource utilization.'
      },
      {
        task: 'Audit Log Cleanup',
        frequency: 'Quarterly',
        description: 'Archive old audit logs based on retention policy.'
      }
    ]
  }
};
